// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/sign-in": {
    params: {};
  };
  "/auth/sign-up": {
    params: {};
  };
  "/verify/:token": {
    params: {
      "token": string;
    };
  };
  "/auth/change-password": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/verify-otp": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/contact-us": {
    params: {};
  };
  "/about-us": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
  "/room/:id": {
    params: {
      "id": string;
    };
  };
  "/booking": {
    params: {};
  };
  "/user-booking": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/sign-in" | "/auth/sign-up" | "/verify/:token" | "/auth/change-password" | "/auth/forgot-password" | "/auth/verify-otp" | "/home" | "/account" | "/profile" | "/blogs" | "/blog/:id" | "/contact-us" | "/about-us" | "/rooms" | "/room/:id" | "/booking" | "/user-booking";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "layouts/main.tsx": {
    id: "layouts/main";
    page: "/auth/sign-in" | "/auth/sign-up" | "/verify/:token" | "/auth/change-password" | "/auth/forgot-password" | "/auth/verify-otp" | "/home" | "/account" | "/profile" | "/blogs" | "/blog/:id" | "/contact-us" | "/about-us" | "/rooms" | "/room/:id" | "/booking" | "/user-booking";
  };
  "layouts/guest.tsx": {
    id: "layouts/guest";
    page: "/auth/sign-in" | "/auth/sign-up" | "/verify/:token" | "/auth/change-password" | "/auth/forgot-password" | "/auth/verify-otp" | "/home" | "/account" | "/profile" | "/blogs" | "/blog/:id" | "/contact-us" | "/about-us" | "/rooms" | "/room/:id" | "/booking" | "/user-booking";
  };
  "pages/auth/sign-in.tsx": {
    id: "pages/auth/sign-in";
    page: "/auth/sign-in";
  };
  "pages/auth/sign-up.tsx": {
    id: "pages/auth/sign-up";
    page: "/auth/sign-up";
  };
  "pages/auth/verified.tsx": {
    id: "pages/auth/verified";
    page: "/verify/:token";
  };
  "pages/auth/change-password.tsx": {
    id: "pages/auth/change-password";
    page: "/auth/change-password";
  };
  "pages/auth/forgot-password.tsx": {
    id: "pages/auth/forgot-password";
    page: "/auth/forgot-password";
  };
  "pages/auth/verify-otp.tsx": {
    id: "pages/auth/verify-otp";
    page: "/auth/verify-otp";
  };
  "pages/public/index.tsx": {
    id: "pages/public/index";
    page: "/home";
  };
  "pages/public/account/index.tsx": {
    id: "pages/public/account/index";
    page: "/account";
  };
  "pages/public/profile/index.tsx": {
    id: "pages/public/profile/index";
    page: "/profile";
  };
  "pages/public/blog/index.tsx": {
    id: "pages/public/blog/index";
    page: "/blogs";
  };
  "pages/public/blog/blog-detail.tsx": {
    id: "pages/public/blog/blog-detail";
    page: "/blog/:id";
  };
  "pages/public/contact.tsx": {
    id: "pages/public/contact";
    page: "/contact-us";
  };
  "pages/public/about.tsx": {
    id: "pages/public/about";
    page: "/about-us";
  };
  "pages/public/rooms/index.tsx": {
    id: "pages/public/rooms/index";
    page: "/rooms";
  };
  "pages/public/rooms/room-detail.tsx": {
    id: "pages/public/rooms/room-detail";
    page: "/room/:id";
  };
  "pages/public/rooms/BookingPage.tsx": {
    id: "pages/public/rooms/BookingPage";
    page: "/booking";
  };
  "pages/public/rooms/user-booking-page.tsx": {
    id: "pages/public/rooms/user-booking-page";
    page: "/user-booking";
  };
  "layouts/protected.tsx": {
    id: "layouts/protected";
    page: "/home";
  };
  "pages/Home/Homeview.tsx": {
    id: "pages/Home/Homeview";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/index": typeof import("./app/pages/index.tsx");
  "layouts/main": typeof import("./app/layouts/main.tsx");
  "layouts/guest": typeof import("./app/layouts/guest.tsx");
  "pages/auth/sign-in": typeof import("./app/pages/auth/sign-in.tsx");
  "pages/auth/sign-up": typeof import("./app/pages/auth/sign-up.tsx");
  "pages/auth/verified": typeof import("./app/pages/auth/verified.tsx");
  "pages/auth/change-password": typeof import("./app/pages/auth/change-password.tsx");
  "pages/auth/forgot-password": typeof import("./app/pages/auth/forgot-password.tsx");
  "pages/auth/verify-otp": typeof import("./app/pages/auth/verify-otp.tsx");
  "pages/public/index": typeof import("./app/pages/public/index.tsx");
  "pages/public/account/index": typeof import("./app/pages/public/account/index.tsx");
  "pages/public/profile/index": typeof import("./app/pages/public/profile/index.tsx");
  "pages/public/blog/index": typeof import("./app/pages/public/blog/index.tsx");
  "pages/public/blog/blog-detail": typeof import("./app/pages/public/blog/blog-detail.tsx");
  "pages/public/contact": typeof import("./app/pages/public/contact.tsx");
  "pages/public/about": typeof import("./app/pages/public/about.tsx");
  "pages/public/rooms/index": typeof import("./app/pages/public/rooms/index.tsx");
  "pages/public/rooms/room-detail": typeof import("./app/pages/public/rooms/room-detail.tsx");
  "pages/public/rooms/BookingPage": typeof import("./app/pages/public/rooms/BookingPage.tsx");
  "pages/public/rooms/user-booking-page": typeof import("./app/pages/public/rooms/user-booking-page.tsx");
  "layouts/protected": typeof import("./app/layouts/protected.tsx");
  "pages/Home/Homeview": typeof import("./app/pages/Home/Homeview.tsx");
};